### ISSUE TITLE
启动后闪退

### ISSUE THREAD

**Issue by h4091** [GameBelial/SimpleReader#1]
android 6.0启动后闪退
09-02 13:46:39.103 28972-28972/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:46:39.104 28972-28983/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:46:39.104 28972-28983/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:46:39.127 28972-28972/com.myzony.zonynovelreader I/Process: Sending signal. PID: 28972 SIG: 9
09-02 13:46:49.629 29101-29112/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:46:49.629 29101-29112/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:46:49.633 29101-29101/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:46:49.651 29101-29101/com.myzony.zonynovelreader I/Process: Sending signal. PID: 29101 SIG: 9
09-02 13:46:50.484 29149-29160/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:46:50.484 29149-29160/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:46:50.487 29149-29149/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:46:50.508 29149-29149/com.myzony.zonynovelreader I/Process: Sending signal. PID: 29149 SIG: 9
09-02 13:46:51.264 29192-29203/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:46:51.264 29192-29203/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:46:51.270 29192-29192/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:46:51.290 29192-29192/com.myzony.zonynovelreader I/Process: Sending signal. PID: 29192 SIG: 9
09-02 13:46:52.099 29239-29239/com.myzony.zonynovelreader I/art: Late-enabling -Xcheck:jni
09-02 13:46:52.140 29239-29250/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:46:52.140 29239-29250/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:46:52.147 29239-29239/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:46:52.168 29239-29239/com.myzony.zonynovelreader I/Process: Sending signal. PID: 29239 SIG: 9
09-02 13:46:53.127 29285-29296/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:46:53.127 29285-29296/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:46:53.137 29285-29285/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:46:53.157 29285-29285/com.myzony.zonynovelreader I/Process: Sending signal. PID: 29285 SIG: 9
09-02 13:47:25.042 29348-29359/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:47:25.042 29348-29359/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:47:25.049 29348-29348/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:47:25.067 29348-29348/com.myzony.zonynovelreader I/Process: Sending signal. PID: 29348 SIG: 9
09-02 13:50:28.932 29711-29711/com.myzony.zonynovelreader I/art: Late-enabling -Xcheck:jni
09-02 13:50:28.980 29711-29723/com.myzony.zonynovelreader I/art: humin current process: com.myzony.zonynovelreader
09-02 13:50:28.981 29711-29723/com.myzony.zonynovelreader I/art: current process_level is : 0
09-02 13:50:28.988 29711-29711/com.myzony.zonynovelreader W/System: ClassLoader referenced unknown path: /data/app/com.myzony.zonynovelreader-1/lib/arm64
09-02 13:50:29.005 29711-29711/com.myzony.zonynovelreader I/Process: Sending signal. PID: 29711 SIG: 9

**Comment by real-zony** [comment]
6.0兼容性没有测试过，在BaseActivty是有一个空指针的ＢＵＧ但是一直没有修复，这个版本已经弃坑了，感谢你的关注。
